spring:
  profiles:
    active: java-client

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

cf:
  debug: false
  verbose: true
  trustApiCerts: false
  trustSelfSignedCerts: false

connection:
  intervalMs: 10000
  delayMs: 1000
