spring:
  profiles:
    active: rest-template

security:
  basic:
    enabled: false

management:
  security:
    enabled: false
    
cf:
  debug: false
  verbose: true

connection:
  intervalMs: 365000
